### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by Koleok** [samybob1/meteor-redux-middlewares#1]
You should put this up on npm as well since there are no real blockers to doing so. I think it’s a pretty good solution btw :)

**Comment by samybob1** [comment]
Hi @Koleok,

I saw your fork, are you going to create a pull request? If you are interested, I can add you as collaborator on this repository. When the package will be published on npm, what do you think I should do with the Atmosphere package?

Thank you!

**Comment by Koleok** [comment]
PR is up 😄 

I think go ahead and leave the atmosphere package for anyone who still prefers to manage their meteor deps that way. We can even bring back all the meteor config files (`.versions`, `package.js` etc..) and just point them differently to the transpiled output in a build-time script

**Comment by samybob1** [comment]
The package is now [available on npm](https://www.npmjs.com/package/meteor-redux-middlewares). I mentioned you in the [credits](https://github.com/samybob1/meteor-redux-middlewares#credits) section and I updated the [demo](https://github.com/samybob1/meteor-redux-middlewares-demo). I tested the [installation with npm](https://github.com/samybob1/meteor-redux-middlewares-demo/tree/npm) and [yarn](https://github.com/samybob1/meteor-redux-middlewares-demo/tree/yarn), everything is working. Finally, I followed your advice and I brought back the meteor config files, so the package is still [available on Atmosphere](https://atmospherejs.com/samy/redux-middlewares) and up to date. Thank you again for your work!
