### ISSUE TITLE
isBrowser returns false in the browser

### ISSUE THREAD

**Issue by samybob1** [samybob1/meteor-redux-middlewares#10]
Hi @Koleok,

I'm working on a new project and I don't know why but in the browser I have a `process` object declared. It seems to be something added by Node. (I'm using v4.6.1)

![screenshot](https://cloud.githubusercontent.com/assets/2417752/21525109/3e8c8282-cd1b-11e6-808b-ada56b314e35.png)

Because of that, our [isBrowser](https://github.com/samybob1/meteor-redux-middlewares/blob/master/src/utils.js#L26) function returns false. Then because of [this bug](https://github.com/meteor/react-packages/issues/99), as we are not running Tracker inside setImmediate, my subscriptions stay on the "not ready" state.

We have to improve the isBrowser function, what do you think about [this solution](http://stackoverflow.com/a/31090240/6917588)?

```js
export const isBrowser = () => {
  try {
    return this === window;
  } catch (e) {
    return false;
  }
};
```

**Comment by Koleok** [comment]
Awesome that is a lot more durable 👍

**Comment by Koleok** [comment]
So maybe we could just tweak it like

```javascript
export const isBrowser = 
  () => typeof window !== 'undefined'
```

**Comment by Koleok** [comment]
The only gotcha would be that `jest` adds in a mocked `window`, so it might bomb some tests

**Comment by samybob1** [comment]
Or we can configure Jest to use the real versions of the timers? [`jest.useRealTimers()`](https://facebook.github.io/jest/docs/api.html#jestuserealtimers)

**Comment by Koleok** [comment]
The browser environment check is actually just an escape hatch after my failed attempts with `useRealTimers` and `mockTimers`, I would love if we could get that working and do away with needing this extra layer of complexity though

**Comment by samybob1** [comment]
Ok, I'll work on it this Wednesday. But for now, I have to merge #12 and #13 to use the package.
