### ISSUE TITLE
Improve test coverage

### ISSUE THREAD

**Issue by samybob1** [samybob1/meteor-redux-middlewares#16]
We have to cover all the branches! 😛 

![capture d ecran de 2017-01-05 17-32-53](https://cloud.githubusercontent.com/assets/2417752/21688414/1379656c-d36d-11e6-847a-1e1d51b588cb.png)

**Comment by Koleok** [comment]
Haha we look awesome from this report 👍

**Comment by Koleok** [comment]
So with the latest master branch jest is crashing for me as if it isn't running through babel

ala
```bash
/Users/Koleok/meteor/meteor-redux-middlewares/src/utils.spec.js:1
    ({"Object.<anonymous>":function(module,exports,require,__dirname,__filename,global,jest){import { isFSA } from 'flux-standard-action';
                                                                                             ^^^^^^
    SyntaxError: Unexpected token import
```

Did some config get knocked out? I never bothered to set this up on circle CI so shame on me, because of that i haven't actually ran the test suite since i last worked on this repo and would have to just look back through commits to see what is up

**Comment by samybob1** [comment]
If you're on the master branch, it's my fault: you have to remove [this part of the babel configuration](https://github.com/samybob1/meteor-redux-middlewares/blob/master/.babelrc#L9) to run the tests. Sorry about that!

I added this because I don't want the jest files to be published on npm when I run `npm run build`, but I fixed the problem by putting the specific configuration inside the [`development` env](https://github.com/samybob1/meteor-redux-middlewares/pull/15/files#diff-e56633f72ecc521128b3db6586074d2cR6). Now we are able to run `test` and `build` without tweaking our babel configuration each time.

**Comment by samybob1** [comment]
414e6ea

**Comment by Koleok** [comment]
Ah forgot about this dangler!
