### ISSUE TITLE
failed to start with meteor 1.5 release build

### ISSUE THREAD

**Issue by tdesc** [samybob1/meteor-redux-middlewares#20]
In debug it works fine
9631145….js?meteor_js_resource=true:23 Uncaught Error: First argument to _arity must be a non-negative integer no greater than ten

**Comment by samybob1** [comment]
Hi, I'll look into it tonight!

**Comment by tdesc** [comment]
It puzzled me as I downgrade to 1.4.4.3 and run meteor --production mode

**Comment by samybob1** [comment]
I [updated the demo to Meteor 1.5](https://github.com/samybob1/meteor-redux-middlewares-demo/commit/30686b470ca0a5a0c96976edabfb66103c53f324) and it's working, I [deployed it on Heroku](https://meteor-redux-middlewares-demo.herokuapp.com/). The package is installed and [imported using npm](https://github.com/samybob1/meteor-redux-middlewares-demo/blob/master/imports/store/index.js#L3):

```js
import /* ... */ from 'meteor-redux-middlewares';
```

I'll now try to run the demo using the Meteor package (it's on the ["meteor" branch](https://github.com/samybob1/meteor-redux-middlewares-demo/blob/meteor/imports/store/index.js#L3)). I'll keep you up to date.

Are you using the npm package? Or the Meteor one?

**Comment by tdesc** [comment]
It seems to be problem with standard-minifier-js
replaced with abernix:standard-minifier-js

**Comment by samybob1** [comment]
It works using the Atmosphere package too, I updated the ["meteor" branch of the demo](https://github.com/samybob1/meteor-redux-middlewares-demo/blob/meteor/imports/store/index.js#L3).

I also tried to run the demo using the production mode (`yarn start -- --production`) and it's working, I can't reproduce your error.

**Comment by samybob1** [comment]
Are you using [standard-minifier-js@2.1.0](https://github.com/samybob1/meteor-redux-middlewares-demo/blob/master/.meteor/packages#L15)?

**Comment by tdesc** [comment]
Yes, it was standard-minifier-js@2.1.0 and I replaced with abernix:standard-minifier-js.

**Comment by samybob1** [comment]
Nice!
