### ISSUE TITLE
Unsubscribe subscription

### ISSUE THREAD

**Issue by otporsad** [samybob1/meteor-redux-middlewares#21]
Hello, this is a great package that simplifies meteor react usage, big tnx to authors! 
I have a small problem with unsubscribing previous subscriptions:

UI click -> load item -> make subscription with item ID, show item (everything works like expected);
Click another item -> because of performance reasons it is not ok to keep old subscriptions/items in minimongo, so I need a way to unsubscribe to old subscription before making a new one.

When i load few items with help of this:
```

var subs = Meteor.default_connection._subscriptions; //all the subscriptions that have been subscribed.

    Object.keys(subs).forEach(function(key) {
        console.log(subs[key]);   // see them in console.
    });
```

I can check active subscriptions. No matter how I tried using `stopSubscription` in combination before loading new item, i can always see previous subscriptions as active. Am I using `stopSubscription `wrong or it is not working?

Example code:

```
export const LoadItem= (id) => {

// For brevity we omit actual check that subscription is ready from redux store
    stopSubscription('item-details');

// Make a new subscription and dispatch action to redux
    return startSubscription({
        key: 'item-details',
        get: () => Items.findOne(id) || null,
        subscribe: () => Meteor.subscribe('item-details', pid)
    });

};
```

**Comment by samybob1** [comment]
Hi, I think you need to use [react-thunk](https://github.com/gaearon/redux-thunk) and to dispatch the `stopSubscription` action:

```js
export const LoadItem = id => {
  return dispatch => {
    // For brevity we omit actual check that subscription is ready from redux store
    dispatch(stopSubscription('item-details'));

    // Make a new subscription and dispatch action to redux
    dispatch(startSubscription({
        key: 'item-details',
        get: () => Items.findOne(id) || null,
        subscribe: () => Meteor.subscribe('item-details', id)
    }));
  };
};
```

Is it working?

**Comment by otporsad** [comment]
Yes that is it, thank you!
