### ISSUE TITLE
Handling multiple subscribers on same key

### ISSUE THREAD

**Issue by fatso83** [samybob1/meteor-redux-middlewares#22]
After looking at the implementation I don't think it handles a quite common scenario: different components triggering the same subscription actions, but where the various components might differ significantly in their respective lifecycles.

Using your example, and a probably common combination with React:

```javascript
export const loadHomePosts = () =>
  startSubscription({
    key: HOME_POSTS_SUB,
    get: () => Posts.find().fetch(),
    subscribe: () => Meteor.subscribe(HOME_POSTS_SUB),
  });
```

If you have two components in different places in a component hierarcy, both needing the home posts, they would probably both trigger `loadHomePosts` in their `componentDidMount` and dispatch `stopHomePosts` in their `componentDidUnmount`. That might cause problems, as this middleware uses the same key for both subscriptions, thus stopping reactive updates for the other component.

How do you propose to work around this? Dynamic keys, handles to stop the right subscription, some kind of reference counting, ...?

**Comment by Koleok** [comment]
I have once or twice handled this issue by using dynamic keys like you mentioned, though I've been able to avoid the need to do so in the majority of cases.

**Comment by LaughingBubba** [comment]
Would this be why I'm getting spurious changes to the subs in redux?

**Comment by fatso83** [comment]
@LaughingBubba That might be. We don't use this middleware today, but I started researching alternatives (such as) as we met this problem in our own solution. There you could see redux display an uneven amount of start/success actions a la:
```
GETTING_FOO_SUB
SUCCESS_FOO_SUB
GETTING_FOO_SUB
STOPPING_FOO_SUB
```
This meant that two components both started subscribing to the same data, but one of them stopped the subscription in its unmount phase, causing the other one never to receive any data, as its `Computation` object had been invalidated by `Tracker`.

That problem will hit this middleware as well, but if you somehow manage to keep the `key`s unique, I guess that would fix it.

**Comment by samybob1** [comment]
We can't handle this inside the lib: let's say you start a sub using key "HOME_POSTS_SUB", so we generate a unique key ("HOME_POSTS_SUB_111"). Then you start a new sub using key "GETTING_FOO_SUB" again, so we generate a new unique key ("HOME_POSTS_SUB_222"). Now, you call `stopSubscription`, how do we determine which subs we should stop?

I think you have to handle the keys generation on your side. If you have a way to differentiate the components that are starting the same sub, it's quite easy. Maybe you can use the components names? If it's the same component that you render several times, you probably already have a way to differentiate them (if you're doing a `.map` somewhere, then you are using some value for the `key` prop?).

Can you share something, a Plunker maybe? So I can help you with the implementation. ;)
