### ISSUE TITLE
`_SUBSCRIPTION_CHANGED ` called after `STOP_SUBSCRIPTION`

### ISSUE THREAD

**Issue by alexpriceonline** [samybob1/meteor-redux-middlewares#23]
I'm pretty sure I've got things wire up properly but the changed and ready events are being called after I stop a subscription. My `STOP_SUBSCRIPTION` reducer removed the `currentUser` from the store, but then _after_ that, the `_SUBSCRIPTION_CHANGED` is called again, re-populating the `currentUser` from the `payload`.

Is this expected behaviour? Have I done something wrong?
Great package, let me know if you need a PR to fix this. Thanks!

**Comment by samybob1** [comment]
Hi Alex, please share your code so we can figure out what's happening!

**Comment by alexpriceonline** [comment]
Hey @samybob1, thanks for your response. So essentially I'm subscribing to the `user` collection which works perfectly:

```
startSubscription({
  key: USER_SELF_SUB,
  get: () => User.find({ _id }).fetch(),
  subscribe: () => Meteor.subscribe(USER_SELF_SUB, _id),
});
```

But when logging out, I call `stopSubscription`:

```
    Meteor.logout(err => {
      if (!err) {
        // Stop watching the redux-middleware subscription
        dispatch(stopSubscription(USER_SELF_SUB));
        dispatch(push('/login'));
      }
    });
```

and see the `STOP_SUBSCRIPTION` action (the reducer un-sets the `currentUser` from the store, but then, after that,  I see, `USER_SELF_SUBSCRIPTION_CHANGED` with `payload: Array(1)` which re-sets the `currentUser` which obviously isn't what I want!

**Comment by alexpriceonline** [comment]
I thought I'd drop in my whole `AppContainer` file so you can see how I'm starting the subscription. I think this is where the problem lies... 

``` javascript
import { Meteor } from 'meteor/meteor';
import { compose } from 'redux';
import { connect } from 'react-redux';
import { withRouter } from 'react-router-dom';
import { withTracker } from 'meteor/react-meteor-data';

import App from '../components/App';
import { fetchUser } from '../modules/actions';
import { SET_LOADING_STATE } from '../modules';

const mapStateToProps = ({ app }) => ({
  loading: app.loading,
  currentUser: app.currentUser,
});

const mapDispatchToProps = dispatch => ({
  init: _id => dispatch(fetchUser(_id)),
  stopLoading: () =>
    dispatch({
      type: SET_LOADING_STATE,
      state: false,
    }),
});

// We need to do this crap becuase we need to wait for
// Meteor to get the current session otherwise Meteor.userId
// isn't available
// https://docs.meteor.com/api/accounts.html#Meteor-loggingIn
const meteorData = withTracker(({ currentUser, init, stopLoading }) => {
  // wait for Meteor to find current user session
  // and then init the store
  if (!currentUser && !Meteor.loggingIn()) {
    if (Meteor.userId()) {
      init(Meteor.userId());
    } else {
      // We get to here when it is an anonymous user.
      // We don't need to load anything in this case,
      // so just stop the loading state
      stopLoading();
    }
  }

  // We have to return an object for withTracker to work
  return {};
});

const reduxData = connect(mapStateToProps, mapDispatchToProps);

export default compose(withRouter, reduxData, meteorData)(App);
```

**Comment by alexpriceonline** [comment]
It must be something to do with `withTracker` re-running after the `Meteor.logout()`. Hmm...

**Comment by alexpriceonline** [comment]
Nope, it's not that as `START_SUBSCRIPTION` isn't being called again. Sorry for the spam updates but it's helping me debug it step by step!

**Comment by alexpriceonline** [comment]
Here's the actions that get triggered on logout:

``` 
STOP_SUBSCRIPTION @ 22:29:43.271
APP/SET_LOADING_STATE @ 22:29:43.271
APP/SET_LOADING_STATE @ 22:29:43.320
@@router/LOCATION_CHANGE @ 22:29:43.357
USER_SELF_SUBSCRIPTION_CHANGED @ 22:29:43.365
USER_SELF_SUBSCRIPTION_READY @ 22:29:43.381
```

I'm stuck now, not sure what else I can check...

**Comment by alexpriceonline** [comment]
Okay so I came up with a fix but I still don't think `meteor-redux-middlewares` is behaving as I'd like...

I moved the `Meteor.userId()` into the actual thunk rather than just passing in a string, so the the subscription has a reactive `userId`, which when `Meteor.logout()` is called, becomes `null` and the subscription returns `Array(0)` which is fine.

I'm still not sure why `USER_SELF_SUBSCRIPTION_READY` and `CHANGED` are bring called post-`STOP_SUBSCRIPTION`... Maybe you have some insight?

```
const fetchUser = () =>
  startSubscription({
    key: USER_SELF_SUB,
    get: () => User.find({ _id: Meteor.userId() }).fetch(),
    subscribe: () => Meteor.subscribe(USER_SELF_SUB, Meteor.userId()),
  });
```

**Comment by alexpriceonline** [comment]
Okay... So I woke up this morning with the realisation that `meteor-redux-middlewares` runs its own internal `withTracker` and so the `Meteor.userId()` is reactive and I can just start the subscription on `App.componentDidMount()` and let it sit listening for changes on `Meteor.userId()`. There is no need for any of my custom `withTracker` + `redux` composing stuff! Closing now <3
