### ISSUE TITLE
About chained subscriptions

### ISSUE THREAD

**Issue by berkaey** [samybob1/meteor-redux-middlewares#24]
Hello there,

I want to chain a subscription but I couldn't find a solution, is there a way to run another subscription (like callback) after the first one. 

ex.

Now, I'm using this below but if user didn't logged in fetchProject still be subscribed.

actions/user.js
```
export const loadUser = () => {
  return function(dispatch) {
    // subscribe extra users' data
    const sub = Meteor.subscribe("users.current", () => {
      // then dispatch to store
      dispatch(
        registerReactiveSource({
          key: "USER",
          get: () => {
            return Meteor.user() || {};
          }
        })
      );

      // and then subscribe for more
      dispatch(fetchProjects());
    });
  };
};
```

actions/projects.js
```
export const USERS_PROJECTS_SUBSCRIPTION_READY =
  "USERS_PROJECTS_SUBSCRIPTION_READY";
export const USERS_PROJECTS_SUBSCRIPTION_CHANGED =
  "USERS_PROJECTS_SUBSCRIPTION_CHANGED";
export const USERS_PROJECTS_SUB = "users.projects";

export const fetchProjects = () =>
  startSubscription({
    key: USERS_PROJECTS_SUB,
    get: () => {
      return Projects.find({ _owner: Meteor.userId() }).fetch();
    },
    subscribe: () => Meteor.subscribe(USERS_PROJECTS_SUB)
  });
```

if I could do this, it will be awesome I guess

ex2.
```      dispatch(
        registerReactiveSource({
          key: "USER",
          get: () => {
            return Meteor.user() || {};
          },
          callback: data => {
            if (data._id) {
              dispatch(fetchProjects());
            }
          }
        })
      );

```

thanks.

**Comment by berkaey** [comment]
btw, for reactive sources it could still doable with 

```
export const loadUser = () => {
  return function(dispatch) {
    // subscribe extra users' data
    const sub = Meteor.subscribe("users.current", () => {
      // then dispatch to store
      dispatch(
        registerReactiveSource({
          key: "USER",
          get: () => {
            return Meteor.user() || {};
          },
          callback: data => {
            if (data._id) {
              dispatch(fetchProjects());
            }
          }
        })
      );
      if (Meteor.userId()) {
        // and then subscribe for more
        dispatch(fetchProjects());
      }
    });
  };
};
```

but with startSubscription ?

**Comment by samybob1** [comment]
Hi,

I think you should have two actions:
- `loadUser`, dispatched when your main component (`ProjectsPageComponent` for instance) is mounted. Inside this main component, you have to render a sub-component (`ProjectsListComponent` for instance) **only if the user is logged in**.
- `loadProjects`, dispatched when your sub-component is mounted.

This way, you don't need any callback within the `registerReactiveSource` function.

What do you think about this solution?

**Comment by berkaey** [comment]
This could actually works on most cases but sometimes that callback could be mandatory like some comments' owners etc. anyhow if you interested in a pull request I tried something like that below and it works for me. ```import { STOP_SUBSCRIPTION, START_SUBSCRIPTION } from "./actions";

import { actionCase } from "./utils";

/*globals
setTimeout
*/

const subscriptions = {};
const computations = {};
const subscriptionsReady = {};

const stopSubscription = action => {
  if (subscriptions[action.payload]) {
    const subscriptionId = subscriptions[action.payload].subscriptionId;

    computations[subscriptionId].stop();
    subscriptions[action.payload].stop();

    computations[subscriptionId] = undefined;
    subscriptions[action.payload] = undefined;
  }
};

export default tracker => ({ dispatch }) => next => action => {
  if (action.type === STOP_SUBSCRIPTION) {
    const stop = () => {
      stopSubscription(action);
    };

    setTimeout(stop);
  } else if (action.type === START_SUBSCRIPTION) {
    const start = () => {
      stopSubscription(action);

      const { key, subscribe, afterReady } = action.payload;
      const subscription = subscribe();
      const { subscriptionId } = subscription;

      subscriptions[key] = subscription;
      computations[subscriptionId] = tracker.autorun(() => {
        const ready = subscription.ready();

        if (ready) {
          dispatch({
            type: `${actionCase(key)}_SUBSCRIPTION_CHANGED`,
            payload: action.payload.get()
          });

          if (afterReady && !subscriptionsReady[subscriptionId])
            afterReady(action.payload.get());
          subscriptionsReady[subscriptionId] = true;
        }

        dispatch({
          type: `${actionCase(key)}_SUBSCRIPTION_READY`,
          payload: {
            ready,
            data: action.payload.onReadyData ? action.payload.onReadyData() : {}
          }
        });
      });
    };

    setTimeout(start);
  }

  return next(action);
};
```

**Comment by berkaey** [comment]
and usage is like
```
export const loadUser = () => {
  return function(dispatch) {
    // subscribe extra users' data
    const sub = Meteor.subscribe("users.current", () => {
      // then dispatch to store
      dispatch(
        registerReactiveSource({
          key: "USER",
          get: () => {
            return Meteor.user() || {};
          }
        })
      );
      if (Meteor.userId()) {
        // and then subscribe for more
        dispatch(fetchProjects());
      }
    });
  };
};
```

**Comment by samybob1** [comment]
Hi @berkaey, please send a PR or close the issue! Thanks
