### ISSUE TITLE
Duplicate Data in minimongo and store

### ISSUE THREAD

**Issue by JamesTheHacker** [samybob1/meteor-redux-middlewares#25]
How do you avoid duplication of data? For example meteor uses minimongo which stores a subset of the data from the database client side. If you use a store to store data based on collection updates then you will have the same data in both the store, and minimongo. Thus duplicate data and double the memory requirements.

Is this a problem and if so how is it solved?

**Comment by samybob1** [comment]
Hi @JamesTheHacker, indeed if you have a lot of data it can be an issue. Maybe you can only store the mongo selectors inside your app state? (even if the state is supposed to be the [single source of truth](https://github.com/reactjs/redux/blob/master/docs/introduction/ThreePrinciples.md#single-source-of-truth))

**Comment by linegel** [comment]
@samybob1 Looks like this issue could be closed :)
