### ISSUE TITLE
Starting a subscription doesn't actually stop the active subscription for that key

### ISSUE THREAD

**Issue by corporealfunk** [samybob1/meteor-redux-middlewares#26]
This particular line of code:

https://github.com/samybob1/meteor-redux-middlewares/blob/414e6eafa17c20d1c17d96568468a8be50574092/src/subscriptions.js#L57

Is meant to stop any active subscriptions for the given publication before the subscription is started. However, the stopSubscriptions function is expecting an object with a single key of "payload" which should contain the publication/subscription name. In the line referenced, however, the code is passing the action that starts the subscription. These "start" types of actions do in fact have payloads, but the payload is an object with data meant to start the subscription, it is not simply the string of the subscription name. Because stopSubscriptions cannot find a subscription with with the key of action.payload, no subscription is stopped.

I've noticed that when re-subscribing to a publication with different parameters (pagination / limit / etc.) that the original subscription still sticks around.

**Comment by samylaumonier** [comment]
Thank you @corporealfunk, I published version 3.0.7 on NPM and Atmosphere 😉
