### ISSUE TITLE
Could it work with  react-native？

### ISSUE THREAD

**Issue by marryton007** [samybob1/meteor-redux-middlewares#6]
I  write a fork of 'meteor-redux-middleware-demo' and want let it work with react-native, but is can't work, any help?

[rntodo](https://github.com/marryton007/rntodo/tree/master)

**Comment by Koleok** [comment]
I would also be interested in getting this working, though I am currently still puzzling on getting the API to a place where it fully makes sense. This should certainly happen though.

**Comment by samybob1** [comment]
Hi @marryton007,

I haven't used react-native yet but it seems that the contributors of [react-native-meteor](https://github.com/inProgress-team/react-native-meteor) are planing to provide a Redux API (inProgress-team/react-native-meteor#147).

Can you commit or send us the code you are using? The repository you linked is empty.

Thank you!

**Comment by marryton007** [comment]
Thanks for reply timely.
I've pushed the code [rntodo](https://github.com/marryton007/rntodo/tree/master)  to github.

**Comment by marryton007** [comment]
I'm try to Modify the 'rntodo/imports/ui/containers/homeContainer.js'  with follow patch 

```
diff --git a/imports/ui/containers/homeContainer.js b/imports/ui/containers/homeContainer.js
index 6c8e1ad..7f0ee3e 100644
--- a/imports/ui/containers/homeContainer.js
+++ b/imports/ui/containers/homeContainer.js
@@ -33,7 +33,11 @@ const mapDispatchToProps = dispatch => {
   }
 }

+const container = createContainer(function(params){
+  return params;
+}, App);
+
 export const HomeContainer = connect(
   mapStateToProps,
   mapDispatchToProps
-)(App)
+)(container)
```

It not working  yet, it seems that the redux can't update the store.

**Comment by Koleok** [comment]
@marryton007 did you get this to work?

**Comment by Koleok** [comment]
I have been pretty slammed with work but if this is still a pain point i fully intend on addressing it at some point as there is plenty of react-native in my life

**Comment by marryton007** [comment]
I pushed the code to  [rntodo](https://github.com/marryton007/rntodo/tree/master).

**Comment by Koleok** [comment]
@marryton007 Awesome, if you want to put up a PR on the `README` for anything specific you had to do to get this working with RN that would certainly be welcome 👍
