### ISSUE TITLE
Is the setTimeout fix needed?

### ISSUE THREAD

**Issue by Koleok** [samybob1/meteor-redux-middlewares#7]
I am having trouble writing tests for these middlewares since the meat of what they do lives in `setTimeout` functions. It occurred to me,  since this is never happening inside a `componentDidMount`, only dispatched from one, why does this fix need to be there?

@samybob1 you would know better since you wrote it, and i'm sure its there for a reason.

**Comment by Koleok** [comment]
Ha I see that it must be needed from [this comment](https://github.com/meteor/react-packages/issues/99#issuecomment-239635704)

**Comment by samybob1** [comment]
The middlewares are not working without this workaround, I don't know exactly why we have to use this `setTimeout` with a 0 ms delay but this is what the react-packages contributor @stubailo [suggested to do](https://github.com/meteor/react-packages/issues/99#issuecomment-168772806). :stuck_out_tongue:

**Comment by Koleok** [comment]
For a workaround for testing I just picked up the environment and skipped the timeout if its not a browser, closing this for now.
