### ISSUE TITLE
COLLECTION__SUBSCRIPTION_CHANGED is never dispatched

### ISSUE THREAD

**Issue by sladkovm** [samybob1/meteor-redux-middlewares#9]
Hi,

I can not get this module working...

0. I have the *store* configured:

```
const configureStore = () => {
  const {
    sources,
    subscriptions,
  } = createReactiveMiddlewares(Tracker);

  const middlewares = [sources, subscriptions, thunk];
  if (process.env.NODE_ENV !== 'production') { // Do not return logging in production
    middlewares.push(createLogger());
  }

  return createStore(
    rootReducer,
    compose(applyMiddleware(...middlewares))
  );
};
```

1. I have a publication set up:

`Meteor.publish('activities', () => Activities.find());`

2. I have created actions:

```
export const ACTIVITIES_SUB = 'activities';
export const ACTIVITIES_SUBSCRIPTION_READY = 'ACTIVITIES_SUBSCRIPTION_READY';
export const ACTIVITIES_SUBSCRIPTION_CHANGED = 'ACTIVITIES_SUBSCRIPTION_CHANGED';
```
and action creator:

```
export const loadActivities = () => {
  // console.log('loadActivities')
  return startSubscription({
    key: ACTIVITIES_SUB,
    get: () => Activities.find().fetch(),
    subscribe: () => Meteor.subscribe(ACTIVITIES_SUB),
  });
};
```

3. I've created reducers:

```
const initialState = {
  ready: false,
  activities: [],
  activitiesSubscriptionStopped: false,
};

export const thunkActivities = (state = initialState, action) => {
  // console.log('Reducer: ', action)
  switch (action.type) {
    case ACTIVITIES_SUBSCRIPTION_READY:
      console.log(action.payload.ready)
      return Object.assign({}, state, { ready: action.payload.ready });
    case ACTIVITIES_SUBSCRIPTION_CHANGED:
      return Object.assign({}, state, { activities: action.payload });
    case STOP_SUBSCRIPTION:
      return action.payload === ACTIVITIES_SUB
        ? Object.assign({}, state, { activitiesSubscriptionStopped: true })
        : state;
    default:
      return state;
  }
};
```

What I see in the log is that `ACTIVITIES_SUBSCRIPTION_READY` is being fired with a *payload.ready* to be set to *false*... After that I see firing of  `START_SUBSCRIPTION` followed by `STOP_SUBSCRIPTION`...

The cycle repeats and subscription never gets *ready* set to *true* and `ACTIVITIES_SUBSCRIPTION_CHANGED` does never fire.

Any thoughts on what I'm doing wrong?

**Comment by Koleok** [comment]
Hey @sladkovm awesome job on summarizing what you have so far 👍 

Not that i think this is necessarily the problem but how/where are you dispatching the action?

**Comment by Koleok** [comment]
Also, you might try putting your `thunk` middleware **first** in the `middlewares` array like
```javascript
const middlewares = [thunk, sources, subscriptions];
``` 

This is a common issue with the thunk middleware as its going to look for any action is a `function`,  if you go about dispatching your `loadActivities` action in an atypical way, the `thunk` middleware may be hijacking it.

**Comment by samybob1** [comment]
Hi @sladkovm,

@Koleok is right, I just created a [reproduction using the code you sent](https://github.com/samybob1/meteor-redux-middlewares-reproduction-issue-9), and it's working!

The major part of the code is [in this file](https://github.com/samybob1/meteor-redux-middlewares-reproduction-issue-9/blob/master/client/main.js) (I know it's dirty, but I had to do it quickly, please **don't** do the same in your project 😛). I don't know exactly where your problem is, but I hope this will help you!

**Comment by sladkovm** [comment]
Thanks, solved...

Before I was trying to dispatch the action from the `render()` or from `componentDidUpdate()` and that did not work.

If I do it as in the reproduction example via the `componentDidMount()` then it works.  Should read React docs more carefully next time ;)

> `componentDidMount()` is invoked immediately after a component is mounted. Initialization that requires DOM nodes should go here. If you need to load data from a remote endpoint, this is a good place to instantiate the network request.
